# application.properties
spring.datasource.url=jdbc:postgresql://cooliedb_asq0_user:45JvQIYtd1jjpS7ZkOLDNAgzT6PXSsTC@dpg-d41ihtf5r7bs739h6gi0-a/cooliedb_asq0
spring.datasource.username=cooliedb_asq0_user
spring.datasource.password=45JvQIYtd1jjpS7ZkOLDNAgzT6PXSsTC