spring.application.name=coolie
spring.datasource.url=jdbc:mysql://<team-db-ip>:3306/coolie_db
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
